dependencies:
- name: nginx-ingress-controller
  version: 5.3.24
  repository: https://charts.bitnami.com/bitnami
- name: minio
  version: 5.0.32
  repository: https://helm.min.io/
- name: proxless
  version: 0.2.0
  repository: file://./vendored_charts/proxless
  condition: proxless.enabled
- name: cert-manager
  version: 0.15.0
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled
- name: argo
  version: 0.9.5
  repository: https://argoproj.github.io/argo-helm
  condition: argo.enabled