apiVersion: v1
kind: Service
metadata:
  name: {{ template "kinto.builder.fullname" . }}
  labels:
    app: {{ template "kinto.fullname" . }}
    chart: {{ template "kinto.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "kinto.builder.fullname" . }}
spec:
  ports:
  - name: "grpc"
    port: {{ .Values.builder.port }}
    protocol: TCP
  selector:
    app: {{ template "kinto.fullname" . }}
    release: {{ .Release.Name }}
    component: {{ template "kinto.builder.fullname" . }}
  type: "ClusterIP"