{{- if empty .Values.builder.workflow.docker.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kinto.workflow.fullname" . }}-docker
  labels:
    app: {{ template "kinto.fullname" . }}
    chart: {{ template "kinto.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "kinto.workflow.fullname" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "workflow-image-registry" . }}
{{- end }}