apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kinto.workflow.fullname" . }}
  labels:
    app: {{ template "kinto.fullname" . }}
    chart: {{ template "kinto.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "kinto.workflow.fullname" . }}
rules:
- apiGroups:
  - ""
  - apps
  - autoscaling
  - rbac.authorization.k8s.io
  - batch
  resources:
  - services
  - endpoints
  - configmaps
  - pods
  - deployments
  - replicasets
  - statefulsets
  - persistentvolumeclaims
  - jobs
  - cronjobs
  - horizontalpodautoscalers
  - rolebindings
  - roles
  - serviceaccounts
  - secrets
  verbs:
  - create
  - update
  - patch
  - delete
  - list
  - watch
  - get
## Below is the bare minimum required by argo
## https://github.com/argoproj/argo/blob/master/docs/workflow-rbac.md#workfow-rbac
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - watch
  - get