apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kinto.builder.fullname" . }}
  labels:
    app: {{ template "kinto.fullname" . }}
    chart: {{ template "kinto.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "kinto.builder.fullname" . }}