{{- if .Values.core.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "kinto.core.fullname" . }}-grpc
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    ## https://github.com/kubernetes/ingress-nginx/issues/2007#issuecomment-656662251
    nginx.ingress.kubernetes.io/server-snippet: "keepalive_timeout 3600s; grpc_read_timeout 3600s; grpc_send_timeout 3600s;client_body_timeout 3600s;"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
  labels:
    app: {{ template "kinto.fullname" . }}
    chart: {{ template "kinto.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "kinto.core.fullname" . }}
spec:
  rules:
  - host: core.{{ .Values.common.domainName }}
    http:
      paths:
      - backend:
          serviceName: {{ template "kinto.core.fullname" . }}
          servicePort: {{ .Values.core.grpc.port }}
  {{- if .Values.common.ssl.enabled }}
  tls:
  - hosts:
    - core.{{ .Values.common.domainName }}
    secretName: {{ template "kinto.core.fullname" . }}-ssl
  {{- end }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "kinto.core.fullname" . }}-grpc-web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800" ## needed for grpc stream
  labels:
    app: {{ template "kinto.fullname" . }}
    chart: {{ template "kinto.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "kinto.core.fullname" . }}
spec:
  rules:
  - host: core-web.{{ .Values.common.domainName }}
    http:
      paths:
      - backend:
          serviceName: {{ template "kinto.core.fullname" . }}
          servicePort: {{ .Values.core.grpcWeb.port }}
  {{- if .Values.common.ssl.enabled }}
  tls:
  - hosts:
    - core-web.{{ .Values.common.domainName }}
    secretName: {{ template "kinto.core.fullname" . }}-ssl
  {{- end }}
{{- end }}