{{- if .Values.core.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kinto.core.fullname" . }}
  labels:
    app: {{ template "kinto.fullname" . }}
    chart: {{ template "kinto.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "kinto.core.fullname" . }}
type: Opaque
data:
  secretKey: {{ .Values.core.secretKey | b64enc | quote }}
{{- end }}