{{- if .Values.common.ssl.enabled }}
{{- if empty .Values.common.ssl.issuer.solver.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kinto.cert-manager.fullname" . }}
  namespace: cert-manager
  labels:
    app: {{ template "kinto.fullname" . }}
    chart: {{ template "kinto.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "kinto.cert-manager.fullname" . }}
type: Opaque
data:
  {{- if .Values.common.ssl.issuer.solver.cloudflare }}
  cloudflareApiToken: {{ .Values.common.ssl.issuer.solver.cloudflare.cloudflareApiToken | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}