apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "kinto.common.fullname" . }}
  labels:
    app: {{ template "kinto.fullname" . }}
    chart: {{ template "kinto.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "kinto.common.fullname" . }}
spec:
  podSelector:
    matchLabels:
  ingress:
    - from:
      - podSelector: {}