apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kinto.common.fullname" . }}
  labels:
    app: {{ template "kinto.fullname" . }}
    chart: {{ template "kinto.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "kinto.common.fullname" . }}
type: Opaque
data:
  {{- if .Values.common.ssl.issuer.solver.cloudflare }}
  cloudflareApiToken: {{ .Values.common.ssl.issuer.solver.cloudflare.cloudflareApiToken | b64enc | quote }}
  {{- end }}