apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kinto.core.fullname" . }}
  labels:
    app: {{ template "kinto.fullname" . }}
    chart: {{ template "kinto.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "kinto.core.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - delete
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
  - list
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - create
- apiGroups:
  - "apps"
  resources:
  - deployments/scale
  verbs:
  - update
- apiGroups:
  - "apps"
  resources:
  - replicasets
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - update
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - update
- apiGroups:
  - "extensions"
  resources:
  - ingresses
  verbs:
  - create
  - get
  - update
  - delete
  - list
- apiGroups:
  - "cert-manager.io"
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - get
  - update
  - delete
- apiGroups:
  - "cert-manager.io"
  resources:
  - issuers
  verbs:
  - create
  - get